UserDir public_html

<Directory "/Users/*/public_html">
    AllowOverride FileInfo AuthConfig Limit Indexes
    Options +MultiViews +Indexes +SymLinksIfOwnerMatch +ExecCGI
    AddHandler cgi-script .cgi
    Require method GET POST OPTIONS
</Directory>
